version: "3.8"
services:
  db:
    image: postgis/postgis:13-3.1-alpine
    container_name: postgres-help-us
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data